/**
 *SafetyPayDirectMiddleLayerV20Lib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/21/2016
 */

'use strict';
angular.module('SafetyPayDirectMiddleLayerV20Lib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "https://api.services.safetypay.com:443/direct/2.0"

    };
});

