/**
 *SafetyPayDirectMiddleLayerV20Lib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/21/2016
 */
/**
 * Creates a instance of Customer
 *
 * @constructor
 */
function Customer() {
    this.id = null;     
    this.name = null;     
    this.lastname = null;     
    this.email = null;     
    this.phone = null;     
}

Customer.prototype = new BaseModel();
Customer.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int|null}
 */
Customer.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {int|null} value 
 */
Customer.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Customer.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string|null} value 
 */
Customer.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Customer.prototype.getLastname = function() {
    return this.lastname;
};

/**
 * Setter for Lastname
 * 
 * @param {string|null} value 
 */
Customer.prototype.setLastname = function(value) {
    this.lastname = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Customer.prototype.getEmail = function() {
    return this.email;
};

/**
 * Setter for Email
 * 
 * @param {string} value 
 */
Customer.prototype.setEmail = function(value) {
    this.email = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Customer.prototype.getPhone = function() {
    return this.phone;
};

/**
 * Setter for Phone
 * 
 * @param {string|null} value 
 */
Customer.prototype.setPhone = function(value) {
    this.phone = value;
};





