/**
 *SafetyPayDirectMiddleLayerV20Lib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/21/2016
 */
/**
 * Creates a instance of User
 *
 * @constructor
 */
function User() {
    this.id = null;     
    this.firstName = null;     
    this.userlogin = null;     
    this.lastName = null;     
    this.email = null;     
    this.password = null;     
    this.phone = null;     
    this.userStatus = null;     
}

User.prototype = new BaseModel();
User.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int|null}
 */
User.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {int|null} value 
 */
User.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getFirstName = function() {
    return this.firstName;
};

/**
 * Setter for FirstName
 * 
 * @param {string|null} value 
 */
User.prototype.setFirstName = function(value) {
    this.firstName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getUserlogin = function() {
    return this.userlogin;
};

/**
 * Setter for Userlogin
 * 
 * @param {string|null} value 
 */
User.prototype.setUserlogin = function(value) {
    this.userlogin = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getLastName = function() {
    return this.lastName;
};

/**
 * Setter for LastName
 * 
 * @param {string|null} value 
 */
User.prototype.setLastName = function(value) {
    this.lastName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getEmail = function() {
    return this.email;
};

/**
 * Setter for Email
 * 
 * @param {string|null} value 
 */
User.prototype.setEmail = function(value) {
    this.email = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getPassword = function() {
    return this.password;
};

/**
 * Setter for Password
 * 
 * @param {string|null} value 
 */
User.prototype.setPassword = function(value) {
    this.password = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getPhone = function() {
    return this.phone;
};

/**
 * Setter for Phone
 * 
 * @param {string|null} value 
 */
User.prototype.setPhone = function(value) {
    this.phone = value;
};

/**
 * User Status
 *
 * @return {int|null}
 */
User.prototype.getUserStatus = function() {
    return this.userStatus;
};

/**
 * Setter for UserStatus
 * 
 * @param {int|null} value 
 */
User.prototype.setUserStatus = function(value) {
    this.userStatus = value;
};





